export const ADD_CONSTRUCTOR_INGREDIENT: 'ADD_CONSTRUCTOR_INGREDIENT' = "ADD_CONSTRUCTOR_INGREDIENT";
export const DELETE_CONSTRUCTOR_INGREDIENT: 'DELETE_CONSTRUCTOR_INGREDIENT' = "DELETE_CONSTRUCTOR_INGREDIENT";
export const SORTED_CONSTRUCTOR: 'SORTED_CONSTRUCTOR' = "SORTED_CONSTRUCTOR";
export const ADD_CONSTRUCTOR_BUN: 'ADD_CONSTRUCTOR_BUN' = "ADD_CONSTRUCTOR_BUN";
