export const GET_INGREDIENTS: 'GET_INGREDIENTS' = "GET_INGREDIENTS";
export const GET_INGREDIENTS_SUCCESS: 'GET_INGREDIENTS_SUCCESS' = "GET_INGREDIENTS_SUCCESS";
export const GET_INGREDIENTS_FAILED: 'GET_INGREDIENTS_FAILED' = "GET_INGREDIENTS_FAILED";
export const CHOICE_INGREDIENT: 'CHOICE_INGREDIENT' = "CHOICE_INGREDIENT";
export const DELETE_INGREDIENT: 'DELETE_INGREDIENT' = "DELETE_INGREDIENT";
export const SET_INGREDIENTS_MODAL: 'SET_INGREDIENTS_MODAL' = 'SET_INGREDIENTS_MODAL';
export const DELETE_INGREDIENTS_MODAL: 'DELETE_INGREDIENTS_MODAL' = 'DELETE_INGREDIENTS_MODAL';