export const SEND_ORDER: 'SEND_ORDER'= "SEND_ORDER";
export const SEND_ORDER_SUCCESS: 'SEND_ORDER_SUCCESS' = "SEND_ORDER_SUCCESS"
export const SEND_ORDER_FAILED: 'SEND_ORDER_FAILED' = "SEND_ORDER_FAILED";
export const GET_ORDER: 'GET_ORDER' = 'GET_ORDER';
export const GET_ORDER_SUCCESS: 'GET_ORDER_SUCCESS' = 'GET_ORDER_SUCCESS';
export const GET_ORDER_FAILED: 'GET_ORDER_FAILED' = 'GET_ORDER_FAILED';